services:
  traversability_estimation:
    container_name: traversability_estimation
    extends: 
      file: common.yaml
      service: .common_nvidia
    volumes:
      - ../world:/world
      - ../traversability_estimation/config:/root/ros2_ws/src/traversability_estimation/traversability_estimation/config
      - ../traversability_estimation/launch:/root/ros2_ws/src/traversability_estimation/traversability_estimation/launch
    command: ros2 launch traversability_estimation traversability_estimation.launch.py use_rviz:=true

  demo:
    container_name: demo
    extends: 
      file: common.yaml
      service: .common_nvidia
    volumes:
      - ../world:/world
      - ../scripts:/scripts
    command: 
      - bash
      - -c
      - |  
          python3 /scripts/obstacles.py /world/obstacles.yaml&
          python3 /scripts/main.py /world/world.stl